import localFont from "next/font/local";
import "./globals.css";
import Ethers from "@/context/EthersContext";
import { Toaster } from "sonner";
import Navbar from "@/components/Components/NavBar";
import AppProvider from "@/components/Components/AppProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider session={session}>
        <Ethers>
          <Navbar />
        {children}
          <Toaster richColors position="top-center" />
        </Ethers>
        </AppProvider>
      </body>
    </html>
  );
}
